config/routes.rb
Rails.application.routes.draw do
  root "snapshots#new"
  resources :snapshots, :except => [:show, :index, :edit]
end

app/models/snapshot.rb
require 'tempfile'
require 'uri'
class Snapshot < ActiveRecord::Base
	before_validation :auto_fix_url
	validates_presence_of :url
	validates_presence_of :email
	has_attached_file :pdf,
						storage: :fog,
						fog_credentials: {
							google_storage_access_key_id: ENV["GOOGLE_KEY_ID"],
							google_storage_secret_access_key: ENV["GOOGLE_SECRET_KEY"],
							provider: 'Google'},
						fog_directory: "pdfsnapshots"
	validates_attachment :pdf, :content_type => { :content_type => "application/pdf"}

	def is_valid_uri?
		request               = Net::HTTP.new(parsed_url.host, parsed_url.port)
		request.use_ssl       = (parsed_url.scheme == 'https')
		response              = request.request_head(parsed_url)
		return true if response.code != '404'
	end	

	def to_pdf
		PdfGenerator.new(self.url).create
	end

	def send_pdf
		PdfMailer.delay.send_pdf(self)
	end

	private

		def parsed_url
			URI.parse(self.url)
		end

		def auto_fix_url
			unless self.url[/\Ahttps:\/\//] || self.url[/\Ahtpp:\/\//]
				self.url = "http://#{ self.url }"
			end
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/snapshots_controller.rb
class SnapshotsController < ApplicationController
  before_action :set_snapshot, only: [:show, :edit, :update, :destroy]

  # GET /snapshots
  # GET /snapshots.json
  def index
    @snapshots = Snapshot.all
  end

  # GET /snapshots/1
  # GET /snapshots/1.json
  def show
  end

  # GET /snapshots/new
  def new
    @snapshot = Snapshot.new
  end

  # GET /snapshots/1/edit
  def edit
  end

  # POST /snapshots
  # POST /snapshots.json
  def create
    @snapshot = Snapshot.new(snapshot_params)
    respond_to do |format|
      if @snapshot.save && @snapshot.is_valid_uri?
        @snapshot.send_pdf
        format.html { redirect_to action: :new, notice: 'Snapshot was successfully created.' }
      else
        format.html { redirect_to action: :new, notice: 'Error: Email and URL are required.'}
      end
    end
  end

  # PATCH/PUT /snapshots/1
  # PATCH/PUT /snapshots/1.json
  def update
    respond_to do |format|
      if @snapshot.update(snapshot_params)
        format.html { redirect_to @snapshot, notice: 'Snapshot was successfully updated.' }
        format.json { render :show, status: :ok, location: @snapshot }
      else
        format.html { render :edit }
        format.json { render json: @snapshot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snapshots/1
  # DELETE /snapshots/1.json
  def destroy
    @snapshot.destroy
    respond_to do |format|
      format.html { redirect_to snapshots_url, notice: 'Snapshot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snapshot
      @snapshot = Snapshot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def snapshot_params
      params.require(:snapshot).permit(:url, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snapshots_helper.rb
module SnapshotsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pdfsnapshot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/snapshots/_form.html.erb
<%= form_for @snapshot do |f| %>
  <% if params[:notice] %>
    <p id="notice" style="background: <%= params[:notice].include?('Error') ? "rgb(203, 11, 11)": "rgb(5, 198, 184)" %>; color: #fff; padding: 15px; font-size: 16px;"><%= params[:notice] %></p>
  <% end %>
  <% if @snapshot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snapshot.errors.count, "error") %> prohibited this snapshot from being saved:</h2>

      <ul>
      <% @snapshot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <%= f.text_field :url, :class => "default-font mdl-textfield__input", :pattern => "^(http[s]?:\\/\\/(www\\.)?|ftp:\\/\\/(www\\.)?|www\\.){1}([0-9A-Za-z-\\.@:%_\+~#=]+)+((\\.[a-zA-Z]{2,3})+)(/(.)*)?(\\?(.)*)?" %>
    <label class="mdl-textfield__label mdl-color-text--white" for="snapshot_url">Url</label>
    <span class="mdl-textfield__error">URL is Invalid. Url should contain http:// or https://</span>
  </div><br>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <%= f.text_field :email, :class => "default-font mdl-textfield__input", :pattern => "^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$" %>
    <label class="mdl-textfield__label mdl-color-text--white" for="snapshot_email">Email Address</label>
    <span class="mdl-textfield__error">Email Address Invalid</span>
  </div>
  <div class="actions">
    <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-ripple--center mdl-color--white mdl-color-text--grey-700" name="commit">
      Snap!
    </button>
  </div>
<% end %>

app/views/snapshots/edit.html.erb
<h1>Editing Snapshot</h1>

<%= render 'form' %>

<%= link_to 'Show', @snapshot %> |
<%= link_to 'Back', snapshots_path %>

app/views/snapshots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Snapshots</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Snapshot link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @snapshots.each do |snapshot| %>
      <tr>
        <td><%= snapshot.url %></td>
        <td><%= snapshot.snapshot_link %></td>
        <td><%= link_to 'Show', snapshot %></td>
        <td><%= link_to 'Edit', edit_snapshot_path(snapshot) %></td>
        <td><%= link_to 'Destroy', snapshot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Snapshot', new_snapshot_path %>

app/views/snapshots/new.html.erb
<div class="form">
	<%= render 'form' %>
</div>

app/views/snapshots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @snapshot.url %>
</p>

<p>
  <strong>Snapshot link:</strong>
  <%= @snapshot.snapshot_link %>
</p>

<%= link_to 'Edit', edit_snapshot_path(@snapshot) %> |
<%= link_to 'Back', snapshots_path %>